# Generated by Django 6.0.6 on 2026-07-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_profilmedecin_profilpatient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilpatient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profilresponsable',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfilMedecin',
        ),
        migrations.DeleteModel(
            name='ProfilPatient',
        ),
        migrations.DeleteModel(
            name='ProfilResponsable',
        ),
    ]
